[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "20"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
